# Generated by Django 4.2.5 on 2023-12-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLASS_NOMER', models.CharField(max_length=50)),
                ('CLASS', models.CharField(max_length=50)),
                ('TV', models.BooleanField(default=True)),
                ('IMG', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=50)),
                ('NOMERA', models.CharField(max_length=50)),
                ('GLAV_STRANICA', models.CharField(max_length=50)),
            ],
        ),
    ]
