# Generated by Django 4.2.5 on 2023-12-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_hotel_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Booked',
            field=models.BooleanField(default=None),
        ),
    ]
