# Generated by Django 4.2.5 on 2023-12-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_hotel_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Booked',
            field=models.BooleanField(verbose_name='Бронирование'),
        ),
    ]
