# Generated by Django 4.2.5 on 2023-12-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_alter_hotel_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Booked',
            field=models.BooleanField(default='Бронирование'),
        ),
    ]
